### ISSUE TITLE
Example using with requirejs

### ISSUE THREAD

**Issue by alexjamesbrown** [ubilabs/geocomplete#106]
Does anyone have an example using Geocomplete with requireJS / pointers to how I could get it working?

**Comment by pcompassion** [comment]
this seems to have a bug. you can't guarantee the correctness of the order

**Comment by alexjamesbrown** [comment]
@pcompassion - correctness of the order? what do you mean by that?

**Comment by cmwelsh** [comment]
I don't think there is an issue if geocomplete does *not* require Google Maps API to be loaded first... it just requires that you have the Google Maps API loaded before you call `$.fn.geocomplete`.

However, just for safety, I load it like this...

`config.js`:

        geocomplete: {
            deps: ['jquery', 'lib/gmaps']
        },

`lib/gmaps.js`:

    // convert Google Maps into an AMD module
    define([
        'async!https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false'
    ], function () {
        return window.google.maps;
    });

my app:

    require('geocomplete');
    var $ = require('jquery');

    $('#example').geocomplete();
