### ISSUE TITLE
geocomplete not working when uploaded to Heroku (i.e. production environment)

### ISSUE THREAD

**Issue by djedynak** [ubilabs/geocomplete#151]
I've installed v1.6 of the jquery geocomplete plugin in my rails 4 app.

It works perfectly when running on my localhost, but when I upload my app to heroku, the autocomplete doesn't work. There don't appear to be any errors, but typing in the autocomplete field doesn't bring up any autocomplete options.

Has any one had a similar problem?

**Comment by Misha86** [comment]
Hi, I have same problem in django + heroku. Can you help me?
