### ISSUE TITLE
multiple autocomplete search types?

### ISSUE THREAD

**Issue by aliz7** [ubilabs/geocomplete#161]
I need to restrict my search box to Cities and Addresses. So the biggest result type should be a City.
When using types: ["(cities)"] it only shows Cities, types: ["address"] it only shows addresses, but I need to show both.

![geocomplete_types](https://cloud.githubusercontent.com/assets/7139699/4779622/7d7ee0aa-5c3b-11e4-9a99-6acd604ecaf6.png)

The "types" option is defined as an Array containing one or more of the supported types for the places request. Does this mean I can define types as cities & address?
How may I define multiple types?

Thanks!

**Comment by jshimko** [comment]
Should be `types: ["cities", "addresses"]`

**Comment by aliz7** [comment]
["cities", "addresses"] doesn't work!
tried ["(cities)", "address"] and it didnt work.
["(cities)"] alone works and ["address"] alone works...
but when I combine them I get no results!
