### ISSUE TITLE
Some locations not loading

### ISSUE THREAD

**Issue by yashwanthbabu** [ubilabs/geocomplete#199]
Hello
http://ubilabs.github.io/geocomplete/examples/form.html
In the above example, i can search all the address i want. But after integrating the geocomplete into my Django project, some of the locations were missing on search. I mean, Some addresses are not showing after integration

Is there any way to overcome with this?

**Comment by tyshkev** [comment]
Add property types: ["geocode", "establishment"] to geocode constructor

**Comment by MehrasT** [comment]
Hey @tyshkev  Can you tell me how to add property types: ["geocode", "establishment"] to geocode constructor to Geocode constructor?

you input will be really helpfull for us

**Comment by MehrasT** [comment]
@tyshkev i added types to constructor but they Return ADdress now when selected

**Comment by yashwanthbabu** [comment]
@tyshkev Thanks. Works great
