### ISSUE TITLE
Postal code not returned when entering a city name

### ISSUE THREAD

**Issue by jeroenvanhaeverbeke** [ubilabs/geocomplete#200]
Something strange I found out:

When you enter a city, no postal code is returned: eg. "New York City". 
But when you enter a street and a city: eg. "Times Square, New York City" the 
plugin is returning a zipcode.
It seems odd to me when you enter a city, that the postal code can't be returned, while a postal
code is linked on a city name...

Example: http://ubilabs.github.io/geocomplete/examples/form.html

Is there a reason for this, because to me it seems like a(n) inconsistency / bug?

**Comment by aemkei** [comment]
This is because a ZIP  code must be unique to show up in the field. 
As "New York City" has a wide range of zip codes, we can't show it.

**Comment by jeroenvanhaeverbeke** [comment]
In most European countries one city has one postal code, so it is quite annoying that I can't grab this when only a city is entered.
