### ISSUE TITLE
Json encode

### ISSUE THREAD

**Issue by garygreen** [ubilabs/geocomplete#205]
Is it possible to get a json encode of the geolocation data, rather than have multiple input fields filled in?

Ideally would like to pass a closure to the `details` function so can catch when a location is selected:

```javascript
$("input").geocomplete({
   details: function(geolocation) {
       console.log(geolocation.lat);
   } 
);
```

**Comment by cmwelsh** [comment]
Try this:

            $location.geocomplete(options)
            .bind('geocode:result', function (event, result) {
                var addressComponents = result.address_components;
