### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by Anahkiasen** [ubilabs/geocomplete#238]
The package currently has a `package.json` but it can't be found in the [NPM Registry](https://www.npmjs.com/package/geocomplete). Could it be published there for all of us folks using Browserify/Webpack/etc?

**Comment by th3fallen** [comment]
+1

**Comment by aemkei** [comment]
Thanks for the hint! It is now available here:
https://www.npmjs.com/package/geocomplete
