### ISSUE TITLE
Dynamically change country limiting.

### ISSUE THREAD

**Issue by ajarti** [ubilabs/geocomplete#30]
Hi guys,
              Could I ask if there is anyway to change the limiting country dynamically after instantiation of the component?

Basically I default the plugin to limit geocoding to 'za' (South Africa), my interface allows the user to select another country from a separate dropdown. I want to update the restriction with the new ISO2 without recreating the object so that any further geocode calls are limited to the new country.

Any help would be appreciated.

David.

**Comment by thiwankalk** [comment]
sammyfa :100:  you are the person many thanks.

ajarti :100:  Thank you ask this question. Many thanks.
