### ISSUE TITLE
Random error "google is not defined"

### ISSUE THREAD

**Issue by kamov** [ubilabs/geocomplete#304]
Sometime randomly I get error "ReferenceError: google is not defined"
Refreshing page, work fine.
Any idea what can be? Thanks

**Comment by aemkei** [comment]
You have to make sure, that the Google Maps API was loaded before the Geocomplete script. So, first wait until the Google Maps API is loaded and then include your this file

**Comment by kamov** [comment]
Thanks for info.
According to this:
http://stackoverflow.com/questions/832692/how-can-i-check-whether-google-maps-is-fully-loaded#7262773

I do something like:

```js
    $("#location").geocomplete({
        map: ".mapcanvas",
        details: "form ",
        markerOptions: {
            draggable: true
        }
    }).bind("geocode:result", function(event, result){
        map = $("#location").geocomplete("map");
        google.maps.event.addListenerOnce(map, 'idle', function() {
            google.maps.event.trigger(map, 'resize');
            map.setZoom(14);    
            map.setCenter(result.geometry.location);
        });
    });
```

Seem work fine now, however, sometime autocomplete not work in firefox

**Comment by katiemccann** [comment]
@aemkei Can you suggest the best way to ensure that the Google Maps API is loaded ahead of the Geocomplete script? I've suddenly started getting this error about 50% of the time now and I'm a JQuery newbie, so not sure how to best guard against it.

**Comment by kamov** [comment]
@katiemccann be sure to not use async="async" when you include google map script. when I removed this, issue never appear.
