### ISSUE TITLE
Reverse geocoding on draggable

### ISSUE THREAD

**Issue by heberuriegas** [ubilabs/geocomplete#42]
http://ubilabs.github.com/geocomplete/examples/draggable.html

After drag the marker should be address be updated, but didnt work.

**Comment by fieldly** [comment]
Is it possible to get updated address data in a simple way on this event?

**Comment by canfiax** [comment]
+1 I would like this aswell

**Comment by Gitesh502** [comment]
$("#geocomplete").bind("geocode:dragged", function (event, latLng)
            {

                var latlng = new google.maps.LatLng(latLng.lat(), latLng.lng());
                var geocoder = geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'latLng': latlng }, function (results, status)
                {
                    if (status == google.maps.GeocoderStatus.OK)
                    {
                      


                        if (results[0])
                        {

                            $("#geocomplete").val(results[0].formatted_address)
                            console.log(results[0])
                            $.each(results[0].address_components, function (index, data)
                            {
                                if (data.types[0] == "country")
                                {
                                    $("#country").val(data.long_name)
                                    console.log("Country =" + data.long_name)
                                }
                                if (data.types[0] == "administrative_area_level_1")
                                {
                                    $("#administrative_area_level_1").val(data.long_name)
                                    console.log("State =" + data.long_name)
                                }
                                if (data.types[0] == "administrative_area_level_2")
                                {
                                    $("#administrative_area_level_2").val(data.long_name)
                                    console.log("District=" + data.long_name)
                                }
                                if (data.types[0] == "administrative_area_level_3")
                                {
                                    $("#administrative_area_level_3").val(data.long_name)
                                    console.log("City=" + data.long_name)
                                }
                                if (data.types[0] == "country")
                                {
                                    console.log("Country=" + data.long_name)
                                }
                                if (data.types[0] == "postal_code")
                                {
                                    $("#postal_code").val(data.long_name)
                                    console.log("postal_code=" + data.long_name)
                                }
                                //alert("Location: " + results[1].formatted_address);
                            });
                        }
                    }
                });
