### ISSUE TITLE
Changing Country

### ISSUE THREAD

**Issue by ShaneOsborne** [ubilabs/geocomplete#79]
Good morning

Is their anyway to change the country once it has been initialised.

I have  the following

```
    $(function () {
        $("#Where").geocomplete({
            types: ['(regions)'],
            country: $("#Country").val(),
            details: "form"
        });
    });
```

On the page but also want to add a onchange event to a select box e.g.

$('#Country').change(function () {
            $("#Where").geocomplete({
                types: ['(regions)'],
                country: $("#Country").val(),
                details: "form"
            });
        });

This code does not work and cannot see how to just set the country without trying to reinitialise again ?

Any help appreciated

Thanks

Shane

**Comment by Jayaramki** [comment]
getting `Uncaught TypeError: $(...).geocomplete(...).setComponentRestrictions is not a function` when I tried `setComponentRestrictions()` method`. Any library need to make work this?
