### ISSUE TITLE
result disappear while moving to next input

### ISSUE THREAD

**Issue by itamar** [ubilabs/geocomplete#91]
While having two fields, the first is 'geocompleted' and the second is standard input, clicking the Enter key geocoding the address but after clicking the Tab key or clicking on the second field, the address dissapear.

I created a snippet:
http://jsfiddle.net/9mj6t/
1. Fill the first field with some info (just write 'ny') 
2. Click Enter (don't pick from list) to enter that partial address.
3. Click Tab to move to the next input field.

you'll see the value returns to be what we enter before.

**Comment by gddabe** [comment]
bump again, any suggestion on this bug?
